//! Generate skeleton `.d.sqfts` from Arma `CfgFunctions` / `Functions.h`.

use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use regex::Regex;

/// Options for declaration generation.
#[derive(Debug, Clone)]
pub struct DeclgenOptions {
    /// Path to `Functions.h` or a file containing `CfgFunctions`.
    pub config_file: PathBuf,
    /// Directory used to resolve `file = "..."` paths (usually the mission / addon root).
    pub resolve_root: PathBuf,
    /// Fallback tag when a group has no `tag = "..."`.
    pub tag_default: String,
    /// When true, only parse inside `class CfgFunctions { ... }`.
    pub cfg_functions_only: bool,
    /// Optional leading path segments to strip from `file = "..."` before resolving
    /// under `resolve_root` (e.g. `"addon_name/"`). Useful when config paths include
    /// an addon/PBO prefix that is not present on disk. Prefer configuring these in
    /// `sqfts.toml` under `[declgen] strip_prefixes`.
    pub strip_prefixes: Vec<String>,
}

/// One generated `declare function` line (plus section metadata).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedDecl {
    pub section: String,
    pub tag: String,
    pub name: String,
    pub full_name: String,
    pub params_src: String,
    pub source_file: Option<PathBuf>,
}

/// Parse the config and emit `.d.sqfts` text.
pub fn generate_declarations(opts: &DeclgenOptions) -> Result<(String, Vec<GeneratedDecl>)> {
    let text = std::fs::read_to_string(&opts.config_file)
        .with_context(|| format!("reading {}", opts.config_file.display()))?;
    let body = if opts.cfg_functions_only {
        extract_cfg_functions_body(&text)?
    } else {
        text
    };
    let entries = parse_cfg_functions(&body, &opts.tag_default)?;
    let mut decls = Vec::new();
    for e in entries {
        let sqf = resolve_sqf_path(
            &opts.resolve_root,
            &e.file_dir,
            &e.fn_name,
            &opts.strip_prefixes,
        );
        let params_src = match &sqf {
            Some(p) if p.is_file() => infer_params_from_sqf(p).unwrap_or_else(|| "()".into()),
            _ => "()".into(),
        };
        let full_name = format!("{}_fnc_{}", e.tag, e.fn_name);
        decls.push(GeneratedDecl {
            section: e.section,
            tag: e.tag,
            name: e.fn_name,
            full_name,
            params_src,
            source_file: sqf,
        });
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by `sqfts declgen`. Tighten types by hand.\n");
    out.push_str(&format!(
        "// Source: {}\n\n",
        opts.config_file.display()
    ));

    let mut current_section = String::new();
    for d in &decls {
        if d.section != current_section {
            current_section = d.section.clone();
            out.push_str(&format!("// --- {} ---\n", d.section));
        }
        out.push_str(&format!(
            "declare function {}{}: any;\n",
            d.full_name, d.params_src
        ));
    }
    Ok((out, decls))
}

#[derive(Debug)]
struct FnEntry {
    section: String,
    tag: String,
    file_dir: String,
    fn_name: String,
}

fn extract_cfg_functions_body(text: &str) -> Result<String> {
    let re = Regex::new(r"(?i)class\s+CfgFunctions\s*\{").unwrap();
    let Some(m) = re.find(text) else {
        bail!("no `class CfgFunctions` found");
    };
    let start = m.end();
    let end = find_matching_brace(text, start - 1)?;
    Ok(text[start..end].to_string())
}

fn find_matching_brace(text: &str, open_idx: usize) -> Result<usize> {
    let bytes = text.as_bytes();
    if open_idx >= bytes.len() || bytes[open_idx] != b'{' {
        bail!("expected '{{' at index {open_idx}");
    }
    let mut depth = 0i32;
    let mut i = open_idx;
    let mut in_string = false;
    let mut string_ch = b'"';
    while i < bytes.len() {
        let c = bytes[i];
        if in_string {
            if c == string_ch && (i == 0 || bytes[i - 1] != b'\\') {
                in_string = false;
            }
            i += 1;
            continue;
        }
        match c {
            b'"' | b'\'' => {
                in_string = true;
                string_ch = c;
            }
            b'/' if i + 1 < bytes.len() && bytes[i + 1] == b'/' => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            b'/' if i + 1 < bytes.len() && bytes[i + 1] == b'*' => {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i += 2;
                continue;
            }
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Ok(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    bail!("unbalanced braces in config");
}

fn parse_cfg_functions(text: &str, tag_default: &str) -> Result<Vec<FnEntry>> {
    // Strip line comments for simpler scanning
    let cleaned = strip_line_comments(text);
    let mut entries = Vec::new();
    let class_re = Regex::new(r"(?i)\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{").unwrap();
    let tag_re = Regex::new(r#"(?i)\btag\s*=\s*"([^"]+)""#).unwrap();
    let file_re = Regex::new(r#"(?i)\bfile\s*=\s*"([^"]+)""#).unwrap();
    let fn_re = Regex::new(r"(?i)\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:\{[^}]*\}|;)").unwrap();

    // Walk top-level groups inside the body
    let mut search_from = 0usize;
    while let Some(m) = class_re.find_at(&cleaned, search_from) {
        let caps = class_re.captures(&cleaned[m.start()..]).unwrap();
        let group_name = caps.get(1).unwrap().as_str().to_string();
        let open = m.end() - 1;
        let close = match find_matching_brace(&cleaned, open) {
            Ok(c) => c,
            Err(_) => break,
        };
        let group_body = &cleaned[open + 1..close];
        let tag = tag_re
            .captures(group_body)
            .map(|c| c.get(1).unwrap().as_str().to_string())
            .unwrap_or_else(|| tag_default.to_string());

        // Nested sections: class Section { file = "..."; class fn {}; }
        let mut sec_from = 0usize;
        while let Some(sm) = class_re.find_at(group_body, sec_from) {
            let scaps = class_re.captures(&group_body[sm.start()..]).unwrap();
            let section_name = scaps.get(1).unwrap().as_str().to_string();
            // Skip if this is `tag` somehow — no, tag is assignment
            let s_open = sm.end() - 1;
            let s_close = match find_matching_brace(group_body, s_open) {
                Ok(c) => c,
                Err(_) => {
                    sec_from = sm.end();
                    continue;
                }
            };
            let section_body = &group_body[s_open + 1..s_close];
            let file_dir = file_re
                .captures(section_body)
                .map(|c| c.get(1).unwrap().as_str().replace('/', "\\"))
                .unwrap_or_default();

            for fc in fn_re.captures_iter(section_body) {
                let fn_name = fc.get(1).unwrap().as_str();
                // Skip the section's own nested class keyword noise — fn_re matches
                // `class X {};` and `class X { ... }` including file/preInit properties.
                // Exclude if the match body looks like a nested section (has `file =`).
                let whole = fc.get(0).unwrap().as_str();
                if file_re.is_match(whole) && whole.contains('{') {
                    // Could be `class settings { headerType = -1; }` — still a function.
                    // Only skip if it contains nested `class `.
                    if Regex::new(r"(?i)\bclass\s+\w+")
                        .unwrap()
                        .find_iter(whole)
                        .count()
                        > 1
                    {
                        continue;
                    }
                }
                // Don't treat the outer section class as a function — already handled.
                if fn_name.eq_ignore_ascii_case(&section_name) {
                    continue;
                }
                entries.push(FnEntry {
                    section: format!("{group_name}/{section_name}"),
                    tag: tag.clone(),
                    file_dir: file_dir.clone(),
                    fn_name: fn_name.to_string(),
                });
            }
            sec_from = s_close + 1;
        }
        search_from = close + 1;
        let _ = group_name;
    }
    Ok(entries)
}

fn strip_line_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        let trimmed = if let Some(i) = line.find("//") {
            // crude: ignore // inside strings by checking odd quotes before
            let before = &line[..i];
            let quotes = before.matches('"').count();
            if quotes % 2 == 0 {
                before
            } else {
                line
            }
        } else {
            line
        };
        out.push_str(trimmed);
        out.push('\n');
    }
    out
}

fn resolve_sqf_path(
    root: &Path,
    file_dir: &str,
    fn_name: &str,
    strip_prefixes: &[String],
) -> Option<PathBuf> {
    if file_dir.is_empty() {
        return None;
    }
    let mut dir = file_dir.replace('\\', "/");
    while dir.starts_with('/') {
        dir = dir[1..].to_string();
    }
    // Strip optional leading addon/PBO prefixes so `file = "addon\path"` resolves
    // under `--root` when the on-disk tree omits that prefix.
    for prefix in strip_prefixes {
        let normalized = prefix.replace('\\', "/");
        let with_slash = if normalized.ends_with('/') {
            normalized
        } else {
            format!("{normalized}/")
        };
        if let Some(rest) = dir.strip_prefix(&with_slash) {
            dir = rest.to_string();
            break;
        }
        if let Some(rest) = dir.strip_prefix(with_slash.trim_end_matches('/')) {
            // Exact prefix match with no trailing path — unusual but allow it.
            if rest.is_empty() || rest.starts_with('/') {
                dir = rest.trim_start_matches('/').to_string();
                break;
            }
        }
    }
    let candidates = [
        root.join(&dir).join(format!("fn_{fn_name}.sqf")),
        root.join(&dir).join(format!("fn_{fn_name}.sqfts")),
    ];
    candidates.into_iter().find(|p| p.is_file())
}

/// Infer `(param list)` from a leading `params [...]` in an SQF file.
fn infer_params_from_sqf(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    let params_idx = find_params_array(&text)?;
    let (params_text, _) = params_idx;
    let entries = parse_params_entries(&params_text);
    if entries.is_empty() {
        return Some("()".into());
    }
    let parts: Vec<String> = entries
        .into_iter()
        .enumerate()
        .map(|(i, (name, ty, optional))| {
            let name = sanitize_param_name(&name, i);
            if optional {
                format!("{name}?: {ty}")
            } else {
                format!("{name}: {ty}")
            }
        })
        .collect();
    Some(format!("({})", parts.join(", ")))
}

fn sanitize_param_name(name: &str, index: usize) -> String {
    let n = name.trim().trim_matches('"').trim_matches('\'').trim();
    if n.is_empty() || !is_ident(n) {
        return format!("_arg{index}");
    }
    n.to_string()
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c.is_ascii_alphabetic() => {
            chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
        }
        _ => false,
    }
}

fn find_params_array(text: &str) -> Option<(String, usize)> {
    // Match `params [` (possibly with whitespace/newlines) at statement level
    let re = Regex::new(r"(?i)\bparams\s*\[").ok()?;
    let m = re.find(text)?;
    let start = m.end() - 1; // '['
    let mut depth = 0i32;
    let bytes = text.as_bytes();
    let mut i = start;
    let mut in_string = false;
    while i < bytes.len() {
        let c = bytes[i];
        if in_string {
            if c == b'"' && (i == 0 || bytes[i - 1] != b'\\') {
                in_string = false;
            }
            i += 1;
            continue;
        }
        match c {
            b'"' => in_string = true,
            b'[' => depth += 1,
            b']' => {
                depth -= 1;
                if depth == 0 {
                    let inner = &text[start + 1..i];
                    return Some((inner.to_string(), i));
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

fn parse_params_entries(inner: &str) -> Vec<(String, String, bool)> {
    let mut out = Vec::new();
    // Split top-level comma-separated entries
    for entry in split_top_level(inner) {
        let e = entry.trim().trim_end_matches(',').trim();
        if e.is_empty() {
            continue;
        }
        if e.starts_with('[') {
            // ["_name", default, [guards], ...]
            if let Some(parsed) = parse_array_param(e) {
                out.push(parsed);
            }
        } else if e.starts_with('"') {
            // "_name"
            if let Some(name) = string_lit(e) {
                out.push((name, "any".into(), false));
            }
        }
    }
    out
}

fn split_top_level(s: &str) -> Vec<String> {
    let mut parts = Vec::new();
    let mut cur = String::new();
    let mut depth = 0i32;
    let mut in_string = false;
    for c in s.chars() {
        if in_string {
            cur.push(c);
            if c == '"' {
                in_string = false;
            }
            continue;
        }
        match c {
            '"' => {
                in_string = true;
                cur.push(c);
            }
            '[' => {
                depth += 1;
                cur.push(c);
            }
            ']' => {
                depth -= 1;
                cur.push(c);
            }
            ',' if depth == 0 => {
                parts.push(std::mem::take(&mut cur));
            }
            _ => cur.push(c),
        }
    }
    if !cur.trim().is_empty() {
        parts.push(cur);
    }
    parts
}

fn parse_array_param(e: &str) -> Option<(String, String, bool)> {
    let inner = e.trim().strip_prefix('[')?.strip_suffix(']')?;
    let parts = split_top_level(inner);
    let name = string_lit(parts.first()?.trim())?;
    let has_default = parts.len() >= 2;
    let ty = if parts.len() >= 3 {
        exemplar_array_to_type(parts[2].trim())
    } else {
        "any".into()
    };
    // With a default → optional for declare purposes when we want skeleton;
    // SPEC says defaults remove nothing from body type, but for declarations
    // we mark params with defaults as optional (`?:`) so call sites can omit them.
    Some((name, ty, has_default))
}

fn string_lit(s: &str) -> Option<String> {
    let s = s.trim();
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        Some(s[1..s.len() - 1].to_string())
    } else {
        None
    }
}

fn exemplar_array_to_type(guard: &str) -> String {
    let g = guard.trim();
    if !g.starts_with('[') {
        return "any".into();
    }
    let inner = g.trim_start_matches('[').trim_end_matches(']').trim();
    if inner.is_empty() {
        return "array".into();
    }
    let parts = split_top_level(inner);
    let mut types: Vec<String> = parts
        .iter()
        .map(|p| exemplar_to_type(p.trim()))
        .filter(|t| t != "any" || parts.len() == 1)
        .collect();
    // Size-only guards like `[3]` → array
    if types.len() == 1 && types[0].chars().all(|c| c.is_ascii_digit()) {
        return "array".into();
    }
    types.retain(|t| !t.chars().all(|c| c.is_ascii_digit()));
    types.dedup();
    if types.is_empty() {
        "any".into()
    } else if types.len() == 1 {
        types.pop().unwrap()
    } else {
        types.join(" | ")
    }
}

fn exemplar_to_type(ex: &str) -> String {
    let e = ex.trim();
    match e {
        "0" | "1" | "-1" => "number".into(),
        "\"\"" | "''" => "string".into(),
        "true" | "false" => "boolean".into(),
        "objNull" => "object".into(),
        "grpNull" => "group".into(),
        "[]" => "array".into(),
        "{}" => "code".into(),
        "configNull" => "config".into(),
        "sideUnknown" | "west" | "east" | "independent" | "civilian" => "side".into(),
        "controlNull" => "control".into(),
        "displayNull" => "display".into(),
        "taskNull" => "task".into(),
        "locationNull" => "location".into(),
        "missionNamespace" | "uiNamespace" | "parsingNamespace" => "namespace".into(),
        _ if e.starts_with('"') || e.starts_with('\'') => "string".into(),
        _ if e.parse::<f64>().is_ok() => "number".into(),
        _ if e.starts_with('[') => "array".into(),
        _ if e.starts_with('{') => "code".into(),
        _ => "any".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn parses_functions_h_fixture() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("Functions.h");
        std::fs::write(
            &cfg,
            r#"
class Mission_Client_Core {
	tag = "TAG";
	class Actions {
		file = "core\actions";
		class payFine {};
		class repairDoor { /* props */ };
	};
};
"#,
        )
        .unwrap();
        let actions = dir.path().join("core/actions");
        std::fs::create_dir_all(&actions).unwrap();
        let mut f = std::fs::File::create(actions.join("fn_payFine.sqf")).unwrap();
        writeln!(
            f,
            r#"params [
	["_unit", objNull, [objNull]],
	["_fee", 0, [0]]
];
true
"#
        )
        .unwrap();
        // repairDoor missing → (): any

        let (text, decls) = generate_declarations(&DeclgenOptions {
            config_file: cfg,
            resolve_root: dir.path().to_path_buf(),
            tag_default: "TAG".into(),
            cfg_functions_only: false,
            strip_prefixes: Vec::new(),
        })
        .unwrap();

        assert_eq!(decls.len(), 2);
        assert!(text.contains("declare function TAG_fnc_payFine"));
        assert!(text.contains("_unit?: object") || text.contains("_unit: object"));
        assert!(text.contains("_fee?: number") || text.contains("_fee: number"));
        assert!(text.contains("declare function TAG_fnc_repairDoor(): any;"));
    }

    #[test]
    fn strip_prefix_resolves_addon_layout() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("config.cpp");
        std::fs::write(
            &cfg,
            r#"
class CfgFunctions {
	class Server {
		tag = "SERVER";
		class Actions {
			file = "my_addon\core\actions";
			class payFine {};
		};
	};
};
"#,
        )
        .unwrap();
        let actions = dir.path().join("core/actions");
        std::fs::create_dir_all(&actions).unwrap();
        std::fs::write(actions.join("fn_payFine.sqf"), "params [\"_unit\"];\n").unwrap();

        let (text, decls) = generate_declarations(&DeclgenOptions {
            config_file: cfg,
            resolve_root: dir.path().to_path_buf(),
            tag_default: "SERVER".into(),
            cfg_functions_only: true,
            strip_prefixes: vec!["my_addon/".into()],
        })
        .unwrap();

        assert_eq!(decls.len(), 1);
        assert!(decls[0].source_file.is_some());
        assert!(text.contains("declare function SERVER_fnc_payFine"));
    }

    #[test]
    fn exemplar_mapping() {
        assert_eq!(exemplar_to_type("objNull"), "object");
        assert_eq!(exemplar_to_type("0"), "number");
        assert_eq!(exemplar_array_to_type("[objNull, 0]"), "object | number");
        assert_eq!(exemplar_array_to_type("[[]]"), "array");
    }
}
