//! Apply high-confidence enrichments to arma3-wiki command YAML for upstream PRs.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use serde_yaml::Value as YamlValue;

use crate::diff::{ensure_wiki_commands_dir, DiffReport, Enrichment};
use crate::emit::safe_filename;

/// Result of preparing upstream wiki patches.
#[derive(Debug, Default)]
pub struct WikiUpstreamResult {
    pub applied: usize,
    pub skipped: usize,
    pub commands: Vec<String>,
}

/// Apply enrichments from a `DiffReport` onto wiki YAML and write
/// `out_dir/wiki-upstream/commands/*.yml` plus `PR.md`.
pub fn emit_wiki_upstream(
    report: &DiffReport,
    wiki_commands_dir: &Path,
    out_dir: &Path,
) -> anyhow::Result<WikiUpstreamResult> {
    let dest = out_dir.join("wiki-upstream").join("commands");
    fs::create_dir_all(&dest)?;

    let mut by_cmd: BTreeMap<String, Vec<&Enrichment>> = BTreeMap::new();
    let mut skipped = 0usize;
    for e in &report.enrichments {
        if e.comref_type == "(overload)" || e.comref_type.is_empty() {
            skipped += 1;
            continue;
        }
        by_cmd.entry(e.command.clone()).or_default().push(e);
    }

    let mut result = WikiUpstreamResult {
        skipped,
        ..Default::default()
    };
    let mut pr_sections: Vec<String> = Vec::new();

    for (command, enrichments) in &by_cmd {
        let wiki_path = find_wiki_file(wiki_commands_dir, command);
        let Some(wiki_path) = wiki_path else {
            result.skipped += enrichments.len();
            continue;
        };
        let text = fs::read_to_string(&wiki_path)?;
        let mut root: YamlValue = serde_yaml::from_str(&text)?;
        let mut applied_here = Vec::new();

        for e in enrichments {
            if apply_enrichment(&mut root, e) {
                applied_here.push((*e).clone());
                result.applied += 1;
            } else {
                result.skipped += 1;
            }
        }

        if applied_here.is_empty() {
            continue;
        }

        let out_name = safe_filename(command) + ".yml";
        let out_text = serde_yaml::to_string(&root)?;
        fs::write(dest.join(&out_name), out_text)?;
        result.commands.push(command.clone());

        let mut section = format!("### `{command}`\n\n");
        for e in &applied_here {
            section.push_str(&format!(
                "- `{}`: set type to `{}` ({})\n",
                e.location, e.comref_type, e.note
            ));
        }
        section.push_str(&format!(
            "\nSource wiki file: `{}`\n",
            wiki_path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("?")
        ));
        pr_sections.push(section);
    }

    let mut pr = String::from(
        "# arma3-wiki type enrichments from COMREF\n\n\
         High-confidence patches where arma3-wiki had `Unknown` and COMREF-md\n\
         provided a concrete type. Generated by `comref-extract emit-wiki-patches`.\n\n\
         ## Changes\n\n",
    );
    pr.push_str(&format!(
        "- Applied: {}\n- Skipped (non-param / missing file / failed apply): {}\n- Commands touched: {}\n\n",
        result.applied,
        result.skipped,
        result.commands.len()
    ));
    for s in pr_sections {
        pr.push_str(&s);
        pr.push('\n');
    }
    pr.push_str(
        "\n## Notes\n\n\
         - Only `Unknown` → concrete replacements are included.\n\
         - Type mismatches and missing overloads remain report-only in `patches/`.\n\
         - Please review each command against the Bohemia Interactive COMREF before merging.\n",
    );

    fs::write(out_dir.join("wiki-upstream").join("PR.md"), pr)?;
    Ok(result)
}

/// Load `patches/summary.yml` and emit wiki-upstream from a local wiki cache.
pub fn emit_wiki_upstream_from_out(out_dir: &Path) -> anyhow::Result<WikiUpstreamResult> {
    let summary = out_dir.join("patches").join("summary.yml");
    if !summary.is_file() {
        anyhow::bail!(
            "missing {}; run `comref-extract extract --diff-wiki` first",
            summary.display()
        );
    }
    let text = fs::read_to_string(&summary)?;
    let report: DiffReport = serde_yaml::from_str(&text)?;
    let cache = out_dir.join(".wiki-cache");
    let wiki_dir = ensure_wiki_commands_dir(&cache)?;
    emit_wiki_upstream(&report, &wiki_dir, out_dir)
}

fn find_wiki_file(dir: &Path, command: &str) -> Option<std::path::PathBuf> {
    let candidates = [
        safe_filename(command) + ".yml",
        command.to_string() + ".yml",
        command.to_ascii_lowercase() + ".yml",
    ];
    for c in candidates {
        let p = dir.join(&c);
        if p.is_file() {
            return Some(p);
        }
    }
    let target = command.to_ascii_lowercase();
    let Ok(rd) = fs::read_dir(dir) else {
        return None;
    };
    for entry in rd.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.to_ascii_lowercase() == format!("{target}.yml") {
            return Some(entry.path());
        }
    }
    None
}

fn apply_enrichment(root: &mut YamlValue, e: &Enrichment) -> bool {
    let loc = &e.location;
    let Some(syntax_idx) = parse_syntax_index(loc) else {
        return false;
    };
    let YamlValue::Mapping(root_map) = root else {
        return false;
    };
    let syn_key = YamlValue::String("syntax".into());
    let Some(YamlValue::Sequence(syns)) = root_map.get_mut(&syn_key) else {
        return false;
    };
    let Some(syn) = syns.get_mut(syntax_idx) else {
        return false;
    };

    let wiki_type = comref_type_to_wiki_yaml(&e.comref_type);

    if loc.contains(".return") {
        return set_return_type(syn, wiki_type);
    }
    if let Some(param_name) = loc.split(".param.").nth(1) {
        return set_param_type(syn, param_name, wiki_type);
    }
    false
}

fn parse_syntax_index(loc: &str) -> Option<usize> {
    let start = loc.find('[')? + 1;
    let end = loc.find(']')?;
    loc[start..end].parse().ok()
}

fn set_return_type(syn: &mut YamlValue, new_ty: YamlValue) -> bool {
    let YamlValue::Mapping(map) = syn else {
        return false;
    };
    for key in ["return", "ret"] {
        let k = YamlValue::String(key.into());
        if let Some(ret) = map.get_mut(&k) {
            if replace_unknown_type(ret, new_ty.clone()) {
                return true;
            }
        }
    }
    false
}

fn set_param_type(syn: &mut YamlValue, param_name: &str, new_ty: YamlValue) -> bool {
    let YamlValue::Mapping(map) = syn else {
        return false;
    };
    let target = param_name.to_ascii_lowercase();

    let params_key = YamlValue::String("params".into());
    if let Some(YamlValue::Sequence(list)) = map.get_mut(&params_key) {
        for item in list.iter_mut() {
            if param_name_matches(item, &target)
                && replace_unknown_type_in_param(item, new_ty.clone())
            {
                return true;
            }
        }
    }

    for key in ["left", "right"] {
        let k = YamlValue::String(key.into());
        if let Some(node) = map.get_mut(&k) {
            if set_param_type_in_node(node, &target, new_ty.clone()) {
                return true;
            }
        }
    }
    false
}

fn set_param_type_in_node(node: &mut YamlValue, target: &str, new_ty: YamlValue) -> bool {
    match node {
        YamlValue::Sequence(items) => {
            for item in items {
                if set_param_type_in_node(item, target, new_ty.clone()) {
                    return true;
                }
            }
            false
        }
        YamlValue::Mapping(map) => {
            let item_key = YamlValue::String("Item".into());
            if let Some(item) = map.get_mut(&item_key) {
                if param_name_matches(item, target)
                    && replace_unknown_type_in_param(item, new_ty.clone())
                {
                    return true;
                }
            }
            for key in ["Array", "Infinite"] {
                let k = YamlValue::String(key.into());
                if let Some(inner) = map.get_mut(&k) {
                    if set_param_type_in_node(inner, target, new_ty.clone()) {
                        return true;
                    }
                }
            }
            if param_name_matches(node, target) && replace_unknown_type_in_param(node, new_ty) {
                return true;
            }
            false
        }
        _ => false,
    }
}

fn param_name_matches(node: &YamlValue, target: &str) -> bool {
    let YamlValue::Mapping(map) = node else {
        return false;
    };
    let name_key = YamlValue::String("name".into());
    map.get(&name_key)
        .and_then(|v| v.as_str())
        .is_some_and(|n| n.eq_ignore_ascii_case(target))
}

fn replace_unknown_type_in_param(node: &mut YamlValue, new_ty: YamlValue) -> bool {
    let YamlValue::Mapping(map) = node else {
        return false;
    };
    let type_key = YamlValue::String("type".into());
    let Some(ty) = map.get_mut(&type_key) else {
        return false;
    };
    replace_unknown_type(ty, new_ty)
}

fn replace_unknown_type(ty: &mut YamlValue, new_ty: YamlValue) -> bool {
    if is_unknown(ty) {
        *ty = new_ty;
        true
    } else {
        false
    }
}

fn is_unknown(ty: &YamlValue) -> bool {
    match ty {
        YamlValue::String(s) => {
            s.eq_ignore_ascii_case("Unknown") || s.eq_ignore_ascii_case("Anything")
        }
        YamlValue::Mapping(map) => {
            if map.len() == 1 {
                if let Some((YamlValue::String(k), _)) = map.iter().next() {
                    return k == "Anything" || k == "Unknown";
                }
            }
            let type_key = YamlValue::String("type".into());
            map.get(&type_key).is_some_and(is_unknown)
        }
        YamlValue::Tagged(t) => {
            let tag = t.tag.to_string();
            let tag = tag.trim_start_matches('!');
            tag == "Anything" || tag == "Unknown"
        }
        YamlValue::Sequence(seq) => seq.first().is_some_and(is_unknown),
        _ => false,
    }
}

fn comref_type_to_wiki_yaml(comref: &str) -> YamlValue {
    let s = comref.trim();
    if let Some(rest) = s
        .strip_prefix("Array of ")
        .or_else(|| s.strip_prefix("Array of"))
    {
        let inner = comref_type_to_wiki_yaml(rest.trim());
        let mut map = serde_yaml::Mapping::new();
        let mut inner_map = serde_yaml::Mapping::new();
        inner_map.insert(YamlValue::String("type".into()), inner);
        map.insert(
            YamlValue::String("ArrayUnsized".into()),
            YamlValue::Mapping(inner_map),
        );
        return YamlValue::Mapping(map);
    }
    if s.contains(" or ") {
        let parts: Vec<&str> = s.split(" or ").map(str::trim).collect();
        let mut seq = Vec::new();
        for p in parts {
            let mut m = serde_yaml::Mapping::new();
            m.insert(
                YamlValue::String("type".into()),
                comref_type_to_wiki_yaml(p),
            );
            seq.push(YamlValue::Mapping(m));
        }
        let mut map = serde_yaml::Mapping::new();
        map.insert(YamlValue::String("OneOf".into()), YamlValue::Sequence(seq));
        return YamlValue::Mapping(map);
    }
    let normalized = match s.to_ascii_lowercase().as_str() {
        "number" => "Number",
        "string" => "String",
        "boolean" | "bool" => "Boolean",
        "object" => "Object",
        "array" => "Array",
        "code" => "Code",
        "side" => "Side",
        "group" => "Group",
        "config" => "Config",
        "control" => "Control",
        "display" => "Display",
        "task" => "Task",
        "location" => "Location",
        "namespace" => "Namespace",
        "hashmap" => "HashMap",
        "nothing" => "Nothing",
        "anything" | "unknown" => "Anything",
        "team member" | "teammember" => "TeamMember",
        "script handle" | "scripthandle" => "Script",
        _ if s.chars().next().is_some_and(|c| c.is_uppercase()) => {
            return YamlValue::String(s.to_string());
        }
        other => {
            let mut c = other.chars();
            match c.next() {
                None => return YamlValue::String("Anything".into()),
                Some(f) => {
                    return YamlValue::String(format!("{}{}", f.to_uppercase(), c.as_str()));
                }
            }
        }
    };
    YamlValue::String(normalized.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_comref_array_of() {
        let v = comref_type_to_wiki_yaml("Array of String");
        assert!(matches!(v, YamlValue::Mapping(_)));
    }

    #[test]
    fn replaces_unknown_string() {
        let mut ty = YamlValue::String("Unknown".into());
        assert!(replace_unknown_type(
            &mut ty,
            YamlValue::String("Number".into())
        ));
        assert_eq!(ty, YamlValue::String("Number".into()));
    }
}
